xcodeproj 'FishLampOSX.xcodeproj'

platform :ios, '7.0'


target :"FishLampOSX-iOS-ARC" do
    platform :ios, '7.0'
    pod 'FishLampCore', :path => '../../FishLampCore'
end

target :"FishLampOSX-OSX-32-MRC" do
    platform :osx, '10.6'
    pod 'FishLampCore', :path => '../../FishLampCore'
end

target :"FishLampOSX-OSX-64-MRC" do
    platform :osx, '10.6'
    pod 'FishLampCore', :path => '../../FishLampCore'
end

target :"FishLampOSX-OSX-64-ARC" do
    platform :osx, '10.6'
    pod 'FishLampCore', :path => '../../FishLampCore'
end

target :"FishLampOSX-OSX-Universal-MRC" do
    platform :osx, '10.6'
    pod 'FishLampCore', :path => '../../FishLampCore'
end